export const data = {
    products: [
      {
        id: '1',
        name: 'Slim Fit White Self Stripe Shirt',
        image: '/images/p1.jpg',
        price: 120,
        countInStock: 10,
        rating: 4.5,
        numReviews: 10,
        description: 'Slim Fit White Self Stripe Shirt',
      },
      {
        id: '2',
        name: 'Best T-shirt for summer',
        image: '/images/p2.jpg',
        price: 250,
        countInStock: 0,
        rating: 4.0,
        numReviews: 10,
        description: 'Weekday Perfect Relaxed T-shirt',
      },
      {
        id: '3',
        name: 'Slim Fit Sky Dobby Non-Iron Shirt',
        image: '/images/p3.jpg',
        price: 25,
        countInStock: 15,
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        id: '4',
        name: 'Womens cool t-shirt',
        image: '/images/p4.jpg',
        price: 65,
        countInStock: 5,
        rating: 4.5,
        numReviews: 10,
        description: 'Modern V-Neck T-Shirt',
      },
    ],
  }